### ISSUE TITLE
Add support for EL7

### ISSUE THREAD

**Issue by lorengordon** [plus3it/mcafee-agent-formula#2]
Currently, the formula fails on EL7 due to the `iptables` states:

```
----------
          ID: Allow ePO Mgmt Inbound Port 8591
    Function: iptables.append
      Result: False
     Comment: State 'iptables.append' was not found in SLS 'mcafee-agent.elx'
              Reason: 'iptables' __virtual__ returned False
     Changes:  
```
